### ISSUE TITLE
The display time of the comment should respect the time zone of the client, but now is UTC default.

### ISSUE THREAD

**Issue by shidenggui** [djyde/cusdis#100]
![image](https://user-images.githubusercontent.com/5035364/117945810-4661e900-b341-11eb-8c5a-3e1975b53853.png)

**Comment by djyde** [comment]
👍 I will handle this

**Comment by frostming** [comment]
I would like to help with this issue. Or are you already done with the fix?

**Comment by djyde** [comment]
> I would like to help with this issue. Or are you already done with the fix?

I'm working on it. 🙌

**Comment by djyde** [comment]
I'm going to send a `Date.now().getTimezoneOffset()` to server and manipulate local time by this value. But I found that Prisma schema's DateTime saved in SQLite is not UTC...

**Comment by shidenggui** [comment]
@djyde I think the time zone of the docker version is UTC, so the stored time is also UTC. 
Cusdis can store UTC in server by default and render the time in client's time zone.

**Comment by djyde** [comment]
@shidenggui Fixed on the latest master branch

**Comment by shidenggui** [comment]
@djyde 👏 After update to the latest docker image, the display time is correct.
![image](https://user-images.githubusercontent.com/5035364/117959509-ad39cf00-b34e-11eb-8e24-a44e6b71b7e5.png)
