### ISSUE TITLE
Comment count

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [djyde/cusdis#109]
Petition to add a way to access the comments count, [like we can do with Disqus](https://help.disqus.com/en/articles/1717274-adding-comment-count-links-to-your-home-page).

**Comment by djyde** [comment]
Looks good

**Comment by djyde** [comment]
Done https://cusdis.com/doc#/advanced/show-comment-count

**Comment by candideu** [comment]
Just wanted to say that the comment count widget works great and is so easy to implement. Thank you!
