### ISSUE TITLE
Is Cusdis down?

### ISSUE THREAD

**Issue by RoneoOrg** [djyde/cusdis#114]
Hi there,

the comment section is not appearing anymore, I double-checked on:

- the documentation: https://cusdis.com/doc#/self-host/docker
- roneo.org: https://roneo.org/en/diagrams.net-adding-more-icons-with-font-awesome-twemoji-and-friends/#cusdis_thread
- physichemically.com: https://physichemically.com/blog/2020/04/28/hello-world/#cusdis_thread

Tested on Firefox and Chromium

The console reads:

```
Uncaught ReferenceError: renderMathInElement is not defined
    at (index):574
cusdis.com/api/open/comments?page=1&appId=7e3e0f81-3810-42ca-b465-e7f43ed5c365&pageId=f2c19e2a86eb2e2ccd565b6bb75095cben:1
Failed to load resource: the server responded with a status of 500 ()
```

**Comment by djyde** [comment]
Sorry. I've fixed it.

**Comment by djyde** [comment]
Fortunately, I accidently woke up and saw your issue email. I'm going to get back to sleep now🤣
