### ISSUE TITLE
Is there any way to change the username?

### ISSUE THREAD

**Issue by RiverOnVenus** [djyde/cusdis#139]
Hey, This is a great comment system，Thank you so much for design it

I want to change the Username displayed in the comments

But I can't edit it in the [User settings](https://cusdis.com/user)

Is there any way to change the Username?

Regards.

**Comment by candideu** [comment]
Are you using the self-hosted version or hosted version?

**Comment by RiverOnVenus** [comment]
> Are you using the self-hosted version or hosted version?

hosted version.

**Comment by candideu** [comment]
> hosted version.

The only workaround I know to do this on the hosted version is to create a new Github or Gmail account that has the name that you would like to have on the site comments.

On the self-hosted version, it's just a matter of adding a new user in the database, swapping out the ids in the comments, and deleting the old one.

That said, it's a lot of unnecessary steps, and doesn't allow for people to have different nicknames for different sites. It's weird how there's no option to delete your account either.... Hopefully, the devs will add the option to edit usernames and delete accounts in the hosted version for the next release.

**Comment by RiverOnVenus** [comment]
> > 托管版本。
> 
> 我知道在托管版本上执行此操作的唯一解决方法是创建一个新的 Github 或 Gmail 帐户，该帐户具有您希望在网站评论中使用的名称。
> 
> 在自托管版本上，只需在数据库中添加一个新用户、换出评论中的 id 并删除旧用户即可。
> 
> 也就是说，这是许多不必要的步骤，并且不允许人们为不同的站点使用不同的昵称。 奇怪的是如何也没有删除您的帐户的选项......希望开发人员将在下一个版本的托管版本中添加编辑用户名和删除帐户的选项。

Thank you.

**Comment by RiverOnVenus** [comment]
> > hosted version.
> 
> The only workaround I know to do this on the hosted version is to create a new Github or Gmail account that has the name that you would like to have on the site comments.
> 
> On the self-hosted version, it's just a matter of adding a new user in the database, swapping out the ids in the comments, and deleting the old one.
> 
> That said, it's a lot of unnecessary steps, and doesn't allow for people to have different nicknames for different sites. It's weird how there's no option to delete your account either.... Hopefully, the devs will add the option to edit usernames and delete accounts in the hosted version for the next release.

Thank you:D

**Comment by djyde** [comment]
I'm going to add an option to modify the admin display name

**Comment by RiverOnVenus** [comment]
great!
