### ISSUE TITLE
"powered by Cusdis" is too obvious

### ISSUE THREAD

**Issue by Pathsis** [djyde/cusdis#156]
No offense, and I'm happy to advertise Cusdis, I just want to say that "powered by Cusdis" is too obvious, could it be displayed in a less obvious way, for example, in a lighter color to the far right of the "Comment" button?

Just a hope, please forgive me if I offend you 😊

**Comment by candideu** [comment]
You can make it a lighter colour by editing the CSS.

**Comment by mkyos** [comment]
> You can make it a lighter colour by editing the CSS. See this issue on how to override the CSS (two ways): #137
> 
> You should be selecting class ".text-gray-900", if I'm not mistaken. Here is an example:
> 
> ```
> .text-gray-900 {
> 	color: #cbab6c !important;
> 	font-style: italic !important;
> }
> ```
> 
> Of course, you are free to add whatever color, font-style, font-size, font-family, opacity, etc. that you want. Consult these links for more CSS properties:
> 
> * [CSS Reference - W3 Schools](https://www.w3schools.com/cssref/)
> * [CSS Properties Reference - MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Properties_Reference)

Thank you, but I have no way to override the default CSS, see: https://blog.cusdis.com/changelog-v1.2.1/

**Comment by candideu** [comment]
It's possible to override the css. I did it recently on a site.

As stated before, issue https://github.com/djyde/cusdis/issues/137 lists two methods of overriding the CSS (the issue is from Aug-September of this year, whereas the blog post you shared is from May):

You can either self-host Cusdis on Vercel and Railway ([see this video](https://youtu.be/XHr0oBIA2xA)), and then edit the widget/theme.css file in your code repo. Add all of your overrides in that file.

OR

Host your own version of embeded js instead of using https://cusdis.com/js/cusdis.es.js. In your version, add your own css in the srcdoc (see: https://github.com/djyde/cusdis/issues/137#issuecomment-917591215)

**Comment by iaeiou** [comment]
Additionally, I would prefer "**Comments** powered by Cusdis", because "Powered by Cusdis" does not make it clear that the comments only are managed with Cusdis

**Comment by djyde** [comment]
It sounds reasonable to add an option to determine display "Powered by" message or not.

**Comment by Pathsis** [comment]
> It sounds reasonable to add an option to determine display "Powered by" message or not.

You are so generous! Helping Cusdis spread the word is also a responsibility. Maybe there's a better way:

1. Currently "powered by Cusdis" is prominently displayed at the bottom of the site, as if the whole site were powered by Cusdis. This doesn't stand out on the official website because there is nothing else at the bottom of the page, but it does stand out on other sites.
2. Even if the slogan doesn't appear on the web, email notifications let users know Cusdis.
3. It might be more appropriate to display the slogan in a less prominent way, for example, by placing the slogan (1) in light and smaller font at the far right of the comment count at the top of the comment list, as comment systems like [Giscus](giscus.app) do.

<img width="793" alt="截屏2021-11-22 14 04 17" src="https://user-images.githubusercontent.com/72077265/142808849-e2128dd8-57eb-432a-ac6b-866bd775732b.png">


4. I still think it's urgent to consider how to open up **email notifications**. I think, to clear up some of your doubts, you might consider opening up email notifications for two events :**(1)** comments approved;  **(2)** reply by the administrator,  this must not lead to the problem of spam, and, since visitors leave the mailbox, default is willing to receive email notification, and, since most blog comments in dialogue between visitors and administrators, open email notification for the two events, has been able to meet the demand of most; (3) Finally, consider the further strategy of fully open email notification when a comment has been approved; (4) Provide a link to unsubscribe in the email. I don't think spam should prevent Cusdis from becoming a real alternative to Disqus.

**Comment by djyde** [comment]
Currently I decrease the font size of this text. 

If anyone what to modify this text, here is a trick:

put this code above the widget:

```js
window.CUSDIS_LOCALE.powered_by = "your own content"
```

**Comment by candideu** [comment]
> Currently I decrease the font size of this text.
> 
> If anyone what to modify this text, here is a trick:
> 
> put this code above the widget:
> 
> ```js
> window.CUSDIS_LOCALE.powered_by = "your own content"
> ```

Wow, thank you for this tip! I would have guessed that you would have to self-host it and change the text inside the lang file for the selected language: https://github.com/djyde/cusdis/tree/master/widget/lang

**Comment by iaeiou** [comment]
> Currently I decrease the font size of this text.
> 
> If anyone what to modify this text, here is a trick:
> 
> put this code above the widget:
> 
> ```js
> window.CUSDIS_LOCALE.powered_by = "your own content"
> ```

Thanks! I still want to credit Cusdis, is there a way to show custom **_and localized_** text?
For example: "Comments powered by Cusdis" in english
and in french "Commentaires propulsés par Cusdis"

**Comment by Pathsis** [comment]
> > Currently I decrease the font size of this text.
> > If anyone what to modify this text, here is a trick:
> > put this code above the widget:
> > ```js
> > window.CUSDIS_LOCALE.powered_by = "your own content"
> > ```
> 
> Thanks! I still want to credit Cusdis, is there a way to show custom **_and localized_** text? For example: "Comments powered by Cusdis" in english and in french "Commentaires propulsés par Cusdis"

Agree, arbitrarily set its content, this seems incomprehensible, I wonder Randy's consideration?

**Comment by candideu** [comment]
> > Currently I decrease the font size of this text.
> > If anyone what to modify this text, here is a trick:
> > put this code above the widget:
> > ```js
> > window.CUSDIS_LOCALE.powered_by = "your own content"
> > ```
> 
> Thanks! I still want to credit Cusdis, is there a way to show custom **_and localized_** text? For example: "Comments powered by Cusdis" in english and in french "Commentaires propulsés par Cusdis"

@iaeiou If I'm not mistaken: if you're self-hosting, you can simply edit the lang files in `widget/lang/` for French and English in your own repository: https://github.com/djyde/cusdis/tree/master/widget/lang

**Comment by djyde** [comment]
> > > Currently I decrease the font size of this text.
> > > If anyone what to modify this text, here is a trick:
> > > put this code above the widget:
> > > ```js
> > > window.CUSDIS_LOCALE.powered_by = "your own content"
> > > ```
> > 
> > 
> > Thanks! I still want to credit Cusdis, is there a way to show custom **_and localized_** text? For example: "Comments powered by Cusdis" in english and in french "Commentaires propulsés par Cusdis"
> 
> Agree, arbitrarily set its content, this seems incomprehensible, I wonder Randy's consideration?

I mean if anyone want to change the locale string, can simply by modifying this global variable. I think it's a flexible approach.

**Comment by djyde** [comment]
And for those who don't want to show this text at all, you can do:

```js
window.CUSDIS_LOCALE.powered_by = ""
```

**Comment by djyde** [comment]
I've changed the text to "Comments powered by Cusdis"

**Comment by nielsbrakel** [comment]
window.CUSDIS_LOCALE seems to not exist in my project. Could somebody give an example?

**Comment by nielsbrakel** [comment]
> And for those who don't want to show this text at all, you can do:
> 
> ```js
> window.CUSDIS_LOCALE.powered_by = ""
> ```

This does not work since cusdis checks if the key is not set and replaces it with the default English key.

```
import en from './lang/en'

export function t(key) {
  const LOCALE_KEY = 'CUSDIS_LOCALE'

  const locale = window[LOCALE_KEY] || en

  const content = locale[key] || en[key] // <-- Here
  if (!locale[key]) {
    console.warn(
      '[cusdis]',
      'translation of language key',
      `'${key}'`,
      'is missing.',
    )
  }
  return content
}
Source: I18n.js
```
But you can replace it with an space and then it works:
```
window.CUSDIS_LOCALE.powered_by = " "
```

**Comment by 12nick12** [comment]
Can someone provide an example snippet of where to put this?

**Comment by candideu** [comment]
> Can someone provide an example snippet of where to put this?

@12nick12 You essentially want to follow the [documentation instructions for the i18n](https://cusdis.com/doc#/advanced/i18n), but modify the 2nd script to only change `window.CUSDIS_LOCALE.powered_by = ""`

Here's an example:

```html
<div id="cusdis_thread"
  data-host="https://cusdis.com"
  data-app-id="{{ APP_ID }}"
  data-page-id="{{ PAGE_ID }}"
  data-page-url="{{ PAGE_URL }}"
  data-page-title="{{ PAGE_TITLE }}"
  window.CUSDIS_LOCALE.powered_by = ""
>
<script async src="https://cusdis.com/js/cusdis.es.js"></script>
<script defer>window.CUSDIS_LOCALE = {
    powered_by: 'REPLACEMENT TEXT',
  }</script>
```
