### ISSUE TITLE
Cusdis doesn't start: Cannot read properties of null ('reading uid')

### ISSUE THREAD

**Issue by thumbfighter** [djyde/cusdis#187]
Getting an error when trying to run Cusdis.

```
info  - Loaded env from /home/thumb/cusdis/.env
TypeError: Cannot read properties of null (reading 'uid')
    at getServerSideProps (/home/thumb/cusdis/.next/server/chunks/521.js:42:71)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.renderToHTML (/home/thumb/cusdis/node_modules/next/dist/server/render.js:589:20)
    at async doRender (/home/thumb/cusdis/node_modules/next/dist/server/base-server.js:879:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/home/thumb/cusdis/node_modules/next/dist/server/base-server.js:979:28)
    at async /home/thumb/cusdis/node_modules/next/dist/server/response-cache.js:64:36

```

The dashboard doesn't show the login and shows 500 Internal server error page instead.

**Comment by mikuai39** [comment]
> Getting an error when trying to run Cusdis.
> 
> ```
> info  - Loaded env from /home/thumb/cusdis/.env
> TypeError: Cannot read properties of null (reading 'uid')
>     at getServerSideProps (/home/thumb/cusdis/.next/server/chunks/521.js:42:71)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Object.renderToHTML (/home/thumb/cusdis/node_modules/next/dist/server/render.js:589:20)
>     at async doRender (/home/thumb/cusdis/node_modules/next/dist/server/base-server.js:879:38)
>     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/home/thumb/cusdis/node_modules/next/dist/server/base-server.js:979:28)
>     at async /home/thumb/cusdis/node_modules/next/dist/server/response-cache.js:64:36
> ```
> 
> The dashboard doesn't show the login and shows 500 Internal server error page instead.

The right url is **/api/auth/signin**  , not **/dashboard** .

**Comment by NickoJow** [comment]
Thanks a lot! This helped solve my 500 problem! I was being careless when I was directed to /dashboard, and didn't realise that this is the issue.

> > Getting an error when trying to run Cusdis.
> > ```
> > info  - Loaded env from /home/thumb/cusdis/.env
> > TypeError: Cannot read properties of null (reading 'uid')
> >     at getServerSideProps (/home/thumb/cusdis/.next/server/chunks/521.js:42:71)
> >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> >     at async Object.renderToHTML (/home/thumb/cusdis/node_modules/next/dist/server/render.js:589:20)
> >     at async doRender (/home/thumb/cusdis/node_modules/next/dist/server/base-server.js:879:38)
> >     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/home/thumb/cusdis/node_modules/next/dist/server/base-server.js:979:28)
> >     at async /home/thumb/cusdis/node_modules/next/dist/server/response-cache.js:64:36
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The dashboard doesn't show the login and shows 500 Internal server error page instead.
> 
> The right url is **/api/auth/signin** , not **/dashboard** .

**Comment by djyde** [comment]
Thanks for the feedback. I'm going to fix it

**Comment by djyde** [comment]
889e8dc56c87d732855e22b353d2d6caa7cd7e91 should fix it
