### ISSUE TITLE
Status of project: Website Down

### ISSUE THREAD

**Issue by candideu** [djyde/cusdis#200]
Hello! There is a Cusdis plugin for Publii, and someone over at the Publii forum mentioned that the website seems to have been down for over a week and may be expired: https://forum.getpublii.com/topic/cusdis-project-is-dead/

Is this project still alive?

**Comment by djyde** [comment]
Thanks for you feedback. I'm in hospital this week and forgot to renew the domain. I've renew it now.

**Comment by candideu** [comment]
No worries, and thank you! Hope you feel better soon Randy @djyde

**Comment by candideu** [comment]
No worries, and thank you! Hope you feel better soon Randy @djyde
