### ISSUE TITLE
Sign in with GitHub is not working as expected

### ISSUE THREAD

**Issue by ghost** [djyde/cusdis#201]
Hello,

I made the decision to test Cusdis. So I followed the "Sign in with GitHub" instructions. It requested permission to use the Cusdis app, which I granted. It should then prompt me to start a new project before displaying the dashboard. Instead, it says, "To confirm your identity, sign in with the same account you used originally."

Can you please guide me on how to fix it?

---

**Screenshot 1**

![Screenshot from 2022-05-09 01-53-03](https://user-images.githubusercontent.com/104995690/167313554-3b2ab068-f2e0-4cc5-8574-ba22598e8efc.png)

**Screenshot 2**

![Screenshot from 2022-05-09 01-12-02](https://user-images.githubusercontent.com/104995690/167313262-eb53bdf8-8a96-4c93-97a0-e662eaa3f2f1.png)

**Comment by djyde** [comment]
Did you have another account in Cusdis with the same email address?

**Comment by QuocVi1994** [comment]
你的信我已收到,我会尽快阅览并回复，谢谢你的来信！~
