### ISSUE TITLE
I can't deploy the project on vercel. It may be a package problem, but it needs to be checked

### ISSUE THREAD

**Issue by SUNWUYUAN** [djyde/cusdis#231]
![image](https://user-images.githubusercontent.com/88357633/214022706-9105323e-6c86-466e-8920-afbca9058b90.png)
I didn't make any other settings. This is a direct use

https://vercel.com/new/git/external?repository -url=https%3A%2F%2Fgithub.com%2Fdjyde%2Fcusdis&env=USERNAME,PASSWORD,DB_ URL,JWT_ SECRET&envDescription=Environment% 20variables% 20reference&envLink=https% 3A% 2F% 2Fcusdis. com% 2Fdoc 

deployed project，I have tried several times, and now it can be deployed directly

(The above content is translated into English by Baidu)

**Comment by abisuq** [comment]
https://github.com/djyde/cusdis/issues/228

**Comment by SUNWUYUAN** [comment]
Oh，thanks
