### ISSUE TITLE
i18n Translations

### ISSUE THREAD

**Issue by Mejans** [djyde/cusdis#25]
Hello,

how to contribute with a translation?
Best regards

**Comment by djyde** [comment]
Hi. I haven't separated the language file yet. I will do it later.

**Comment by djyde** [comment]
Hi @Mejans , you can now contribute translation for the widget. Check the documentation: https://cusdis.com/doc#/advanced/i18n

**Comment by djyde** [comment]
I will support internationalize for Dashboard in few days too if I have enough time. Feel free to contribute if anyone want to.
