### ISSUE TITLE
How can I modify the font in Cusdis? 

### ISSUE THREAD

**Issue by iLucis** [djyde/cusdis#255]
How can I make the font of elements such as nickname, email, reply, input box text, and comment content in Cusdis consistent with the font of my website theme?

I have added the code to link the custom.css file for the theme font in the comments.html of Hugo, as shown below. However, only the title and counter text have been changed, as shown in the attached screenshot.

```html
<div>
<h3>Comment</h3>
<span data-cusdis-count-page-id="{{ .File.UniqueID }}">0</span> comments
<div id="cusdis_thread"
  data-host="https://cusdis.com"
  data-app-id="****"
  data-page-id="{{ .File.UniqueID }}"
  data-page-url="{{ .RelPermalink }}"
  data-page-title="{{ .Title }}"
></div>
<link rel="stylesheet" href="custom.css">
</div>
<script defer src ····
```
<img width="987" alt="Snipaste" src="https://github.com/djyde/cusdis/assets/132722267/910be622-052a-434e-b5c9-c87e6acb0bab">

**Comment by sunaiwen** [comment]
It's because Cusdis use `iframe` to display the form for inputting comments, and the css which is outside of the iframe will not have any effect.

Maybe you can fork Cusdis to do your own changes. The relative files are in the `widget` directory. It's all css classes of tailwindcss. So it's quite straightforward to modify.

**Comment by iLucis** [comment]
> It's because Cusdis use `iframe` to display the form for inputting comments, and the css which is outside of the iframe will not have any effect.
> 
> Maybe you can fork Cusdis to do your own changes. The relative files are in the `widget` directory. It's all css classes of tailwindcss. So it's quite straightforward to modify.

Thanks!   I'll try it.
