### ISSUE TITLE
Improve widget css

### ISSUE THREAD

**Issue by djyde** [djyde/cusdis#39]
![image](https://user-images.githubusercontent.com/914329/115735420-0b613b00-a3bd-11eb-8f3e-fdc66f320b01.png)

![image](https://user-images.githubusercontent.com/914329/115735490-19af5700-a3bd-11eb-968d-c3b5666eec55.png)

Ref: https://github.com/djyde/cusdis/pull/33

PR is welcome if someone is good at CSS

**Comment by scag1io** [comment]
Hi, this is my first comment ever on GitHub and I am totally noob using it – please have patience.
My idea for widget CSS: why don't put all the styles (replies, comment, widget) in one separate CSS file? It would be easier to manage.
