### ISSUE TITLE
Duplicate call to CORS?

### ISSUE THREAD

**Issue by garnerp** [djyde/cusdis#4]
https://github.com/djyde/cusdis/blob/0a81a9072da62e7ea1c3cd1df5336f2dc808506f/pages/api/open/comments.ts#L21

Is this a duplicate call to the CORS middleware?

**Comment by djyde** [comment]
Oh yes, I forgot to remove this line of code.

**Comment by garnerp** [comment]
Opened PR #5

**Comment by djyde** [comment]
merged
