### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by egoist** [djyde/cusdis#59]

**Comment by pablopvsky** [comment]
@egoist Are you working on dark mode?

**Comment by egoist** [comment]
nope

Pablo Orozco ***@***.***> 于 2021年4月28日周三 上午6:19写道：

**Comment by djyde** [comment]
Thanks to @craigary , we are support dark mode now.

**Comment by djyde** [comment]
Reopen because still need to deal with the css bundle

**Comment by danisztls** [comment]
Is the auto mode working?

**Comment by djyde** [comment]
I tested it works.

Daniel ***@***.***>於 2021年5月4日 週二，上午8:03寫道：

**Comment by danisztls** [comment]
I see, you're using `prefers-color-scheme: dark` to detect dark mode. That would not work with toggleable dark mode. I would request support for `[data-theme='dark'] {}` but it is not a standard. :)

**Comment by djyde** [comment]
I will make it reactive. Thanks for feedback!

Daniel ***@***.***>於 2021年5月4日 週二，下午12:08寫道：

**Comment by djyde** [comment]
> I see, you're using `prefers-color-scheme: dark` to detect dark mode. That would not work with toggleable dark mode. I would request support for `[data-theme='dark'] {}` but it is not a standard. :)

Hi @danisztls we now support a `setTheme()` API to manually set theme: https://cusdis.com/doc#/advanced/sdk?id=windowcusdissetthemetheme-39dark39-39light39-39auto39
