### ISSUE TITLE
there may be a problem in react sdk sample snippets.

### ISSUE THREAD

**Issue by nodenota** [djyde/cusdis#67]
it should be: 

`import { ReactCusdis } from  @'react-cusdis';` 

：）

<img width="566" alt="微信截图_20210427171719" src="https://user-images.githubusercontent.com/58244032/116217725-7a071580-a77c-11eb-9178-f527a3a691ea.png">

**Comment by djyde** [comment]
Where is this document?

**Comment by nodenota** [comment]
> Where is this document?

https://www.npmjs.com/package/react-cusdis

**Comment by nodenota** [comment]
It was resolved in v2.0.1.
