### ISSUE TITLE
The approve_link from webhook is incorrect while using self-hosting

### ISSUE THREAD

**Issue by waisimon** [djyde/cusdis#82]
I am trying self-host a cusdis app on [vercel](https://cusdis.com/doc#/self-host/vercel)
with custom domains `cusdis.self.host`

1. after I set up a custom webhook link with TGBOT
2. and testing post new comment
3. the `approve_link` from webhook message is `
https://cusdis.com/open/approve?token=xxx`

which is,  `cusdis.com` at approve_link is not matching my custom domains `cusdis.self.host`
and hence cause the `invalid token` error

**Comment by djyde** [comment]
You need to set env variable `HOST` to your own domain (`cusdis.self.host`).

I wrote this tip on the bottom of https://cusdis.com/doc#/features/notification . But I think it should be more obvious. I'll improve the documentation later.

**Comment by waisimon** [comment]
Oh I see,  many thanks.

By the way, can we use `NEXTAUTH_URL` env instead of `HOST` env ? 
since I compare with them and it looks ALL same

Also, I face the `invalid token` after I click the  `approve_link` again, is any configs I was missing?

**Comment by djyde** [comment]
Are you using latest master branch?

Simon Chan ***@***.***>於 2021年5月3日 週一，上午1:39寫道：

**Comment by waisimon** [comment]
sure, I re-deploy again just now and still `invalid token`

Meanwhile, I found the webhook push is not working after a new comment is coming.
I received a push after I click `save` button on portal
![image](https://user-images.githubusercontent.com/26592019/116914143-f5852d00-ac7c-11eb-9420-1861f927309b.png)

**Comment by waisimon** [comment]
finally, i found why it show `invalid token`

a char `\` included at the end of token that make token invalid

```
https://cusdis.self.host/open/approve?token=jwtToken\
```

I remove it manually and it works now.

**Comment by djyde** [comment]
> finally, i found why it show `invalid token`
> 
> a char `\` included at the end of token that make token invalid
> 
> ```
> https://cusdis.self.host/open/approve?token=jwtToken\
> ```
> 
> I remove it manually and it works now.

I see. A typo here https://github.com/djyde/cusdis-telegram-bot/blob/master/index.js#L12 

Will fix it later

**Comment by djyde** [comment]
Hi @waisimon I tested this again and it works fine in telgram bot (the jwt token doesn't inlcude `\`). 
![image](https://user-images.githubusercontent.com/914329/117107336-ff5d7c00-adb3-11eb-91d8-6ad0e8d01ce3.png)

**Comment by waisimon** [comment]
@djyde 
looks great ! I can approve comment now when using official webhook.

However, I am using self webhook robot and it still occur `invalid token`
so I need to self-host webhook server by myself ? or any config I need to config ?

**Comment by djyde** [comment]
> @djyde
> looks great ! I can approve comment now when using official webhook.
> 
> However, I am using self webhook robot and it still occur `invalid token`
> so I need to self-host webhook server by myself ? or any config I need to config ?

I can't sure what wrong with your bot settings. You can refer my implementation in https://github.com/djyde/cusdis-telegram-bot

**Comment by waisimon** [comment]
> > @djyde
> > looks great ! I can approve comment now when using official webhook.
> > However, I am using self webhook robot and it still occur `invalid token`
> > so I need to self-host webhook server by myself ? or any config I need to config ?
> 
> I can't sure what wrong with your bot settings. You can refer my implementation in https://github.com/djyde/cusdis-telegram-bot

Finally it totally works now 
thanks for your help!
