### ISSUE TITLE
About Nested Comment 

### ISSUE THREAD

**Issue by bhaveshmoney** [djyde/cusdis#87]
I want ot know about  the  nested comment  admin can disable or enable option is available in admin dashboard or not.

**Comment by djyde** [comment]
Cusdis is designed for nested comment. We don't have a plan to support non-nested comment.

What's your scenario?

**Comment by bhaveshmoney** [comment]
I know about enable or disable option is applicable in nested comment or not

**Comment by djyde** [comment]
> I know about enable or disable option is applicable in nested comment or not

No.
