### ISSUE TITLE
url link is invalid in doc

### ISSUE THREAD

**Issue by Edwardzcn** [djyde/cusdis#89]
In section `Advanced` subsec `i18n`, the link: https://cusdis.com/js/widget/lang/LANG_CODE.js is invalid.

![image](https://user-images.githubusercontent.com/32711483/117404205-17f89e00-af3c-11eb-9e01-0f1955770948.png)

I'm working on supporting Cusdis in [hexo-theme-fluid](https://github.com/fluid-dev/hexo-theme-fluid) with i18n enable, but too be honest, the guidance in Cusdis documentation is a little bit confusing.

**Comment by djyde** [comment]
Sorry for the confusion. I improved the document, hope it help!

**Comment by Edwardzcn** [comment]
> Sorry for the confusion. I improved the document, hope it help!

Thx!
