### ISSUE TITLE
Comment notification implementation RFC

### ISSUE THREAD

**Issue by djyde** [djyde/cusdis#9]
I'm thinking about how to notify the moderator when a new comment comes in. In this issue I will explain the design I'm considering.

## WebHook (push-based solution)

The simplest way to notify is when new comment is added, we make POST request to the webhook with the comment body.

Every project (website) can set one webhook url.

![image](https://user-images.githubusercontent.com/914329/115708388-80734700-a3a2-11eb-9744-c85533c01408.png)

## Open API for fetching updates batch (pull-based solution)

Another way is exposing an open api for each project. e.g.

```
GET https://cusdis.com/api/projects/xxx/open/new_comments?token=xxxx
```

Every project has a `token` which is generated by system. It can be revoked and re-generate manually.  When user GET this API, the server will do:

1. Get the `latest_fetch_update_date` of the project, fetch all comments between `latest_fetch_update_date` and `now()`
2. Set `latest_fetch_update_date` to `now()`
3. response the comments

This approach is very flexible:

- End user can implement their own cron job for fetching bunch of latest comments and do whatever they want to, instead of receive notification every time new comment comes in.
- Cusdis hosted service could implement own cron job service, send the latest comments to user's email every day.

![image](https://user-images.githubusercontent.com/914329/115707777-c7147180-a3a1-11eb-9a8e-27e4fdeabb02.png)

**Comment by YikSanChan** [comment]
I prefer the API solution. Will the API service be hosted together with the PostgreSQL database, in docker?

**Comment by djyde** [comment]
@YikSanChan Yes it will.

**Comment by YikSanChan** [comment]
@djyde Since I host my blog on Vercel because I hope I don't need to manage some infrastructure for my blog, therefore I am trying to see how the DB + API service fit into my setup.

DB: I can host my PostgreSQL database on Supabase.io, a DB-as-a-service solution.
API service: I am not sure how to host this, maybe leverage Vercel serverless function?

If it is made easy enough to deploy the API service on Vercel, then I think it is a good proposal.

Thank you for your work!

**Comment by djyde** [comment]
@YikSanChan Do you mean deploy Cusdis on Vercel? There is a document about it https://cusdis.com/doc#/self-host/vercel

**Comment by YikSanChan** [comment]
@djyde Hi, I am saying how to deploy the proposed API service with Vercel, if I don't want to deploy with docker.
