### ISSUE TITLE
support switchable dark mode and hexo integration bug

### ISSUE THREAD

**Issue by Edwardzcn** [djyde/cusdis#90]
# Problem Discription

Hi, thx for providing such a lightweight and convenient comment system. 

I've been tring it for a while and it really fits my blog! But there exists some problems.

1. **switchable dark mode**: Cusdis is equipped with dark mode with  `prefers-color-scheme: dark` according to the discussion in #59 . I parse the `theme.dark_mode.default` with value `auto` to `data-theme`, It fails automatically detect the dark(light) mode at the beginning. When I toggle the dark mode button, it also **fails to change dynamically**.
    
    ![image](https://user-images.githubusercontent.com/32711483/117433820-7fbfe080-af5e-11eb-98d5-d408658c6e32.png)

2. **hexo integration bug**(not for sure): I use Cusdis in customized hexo-fluid-theme. But it shows this

    ![image](https://user-images.githubusercontent.com/32711483/117433604-3cfe0880-af5e-11eb-918c-e51fe6b9c67b.png)

# Theme File

Here is my customized theme file:

```ejs
<% if (theme.cusdis.host && theme.cusdis.app_id) { %>
<div class="cusdis"></div>
<div id="cusdis_thread" data-host="<%= theme.cusdis.host %>" data-app-id="<%= theme.cusdis.app_id %>"
  data-page-id="<%= md5(page.path) %>" data-page-url="<%= page.path %>" data-page-title="<%= page.title %>"
  data-theme="<%= theme.dark_mode.default %>">
  <script type="text/javascript">
      var src = 'https://cusdis.com/js/widget/lang/' + '<%= theme.cusdis.lang %>' + '.js'
      Fluid.utils.createScript(src)
    </script>
  <script type="text/javascript">
    Fluid.utils.loadComments('#cusdis_thread', function () {
      Fluid.utils.createScript("<%= url_join(theme.cusdis.host, 'js/cusdis.es.js') %>");
    });
  </script>
</div>

<noscript>Please enable JavaScript to view the comments</noscript>
<% } %>
```

# Blog link

Here is [my blog](https://www.edwardzcn98yx.com/post/adf76b39.html).

**Comment by djyde** [comment]
Ref #91
